name: Prepare repo #@@@
description: Prepare repo for @@@ #@@@
inputs:
  argocd_app:
    description: Application name #@@@
    required: true
  argocd_overlays:
    description: Overlay names (space separated) #@@@
    required: true
  image_tag:
    description: Docker image tag #@@@
    required: true
  commit_ref:
    description: Base Kustomization commit reference #@@@
    required: true
runs:
  using: composite
  steps:
    #@@@ INLINE THE SCRIPT?
    - run: |
        for overlay in "${{ inputs.argocd_overlays }}"; do
          "${{ github.action_path }}/update_app.sh" \
            "${{ inputs.argocd_app }}" \
            "$overlay" \
            "${{ inputs.image_tag }}" \
            "${{ inputs.commit_ref }}";
        fi
      shell: bash
