name: Update app #@@@
description: Update app for @@@ #@@@
inputs:
  ARGOCD_APP:
    description: Application name
    required: true
  ARGOCD_OVERLAYS:
    description: Overlay names (space separated)
    required: true
  IMAGE_TAG:
    description: New docker image tag
    required: true
  BASE_COMMIT_REF:
    description: New base Kustomization commit reference
    required: true
runs:
  using: composite
  steps:
    #@@@ INLINE THE SCRIPT?
    - run: |
        for overlay in ${{ inputs.ARGOCD_OVERLAYS }}; do
          "${{ github.action_path }}/update_app.sh" "${{ inputs.ARGOCD_APP }}" "$overlay" "${{ inputs.IMAGE_TAG }}" "${{ inputs.BASE_COMMIT_REF }}"
        done
      shell: bash
