# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#@@@ RENAME TO MAKE CLEAR IT'S FOR DEV (AND TEST, KIND OF)
#@@@ OR JUST ADD PARAMETERS THAT CAN BE OVERRIDDEN
name: Update and sync ArgoCD
on:
  workflow_call:
    inputs:
      argocd_app:
        description: Application name #@@@
        type: string
        required: true
      argocd_update_overlays:
        description: Update overlay names (space separated) #@@@
        type: string
        default: dev
      argocd_promote_overlays:
        description: Promote overlay names (space separated) #@@@
        type: string
        default: test
      image_tag:
        description: Docker image tag #@@@
        type: string
        required: true
      commit_ref:
        description: Base Kustomization commit reference #@@@
        type: string
        required: true

jobs:
  build:
    name: Deploy #@@@
    runs-on: ubuntu-latest #@@@ [self-hosted, linux]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Configure repo #@@@
        uses: borsboom/seal-github-secrets-action/.github/actions/config_repo@main #@@@
      - name: Update app #@@@
        uses: borsboom/seal-github-secrets-action/.github/actions/update_app@main #@@@
        with:
          argocd_app: ${{ inputs.argocd_app }}
          argocd_overlays: ${{ inputs.argocd_update_overlays }}
          image_tag: ${{ inputs.image_tag }}
          commit_ref: ${{ inputs.commit_ref }}
      - name: Promote app #@@@
        uses: borsboom/seal-github-secrets-action/.github/actions/promote_app@main #@@@
        with:
          argocd_app: ${{ inputs.argocd_app }}
          argocd_from_overlay: ${{ inputs.argocd_update_overlays }}
          argocd_to_overlays: ${{ inputs.argocd_promote_overlays }}
      - name: Push repo @@@
        uses: borsboom/seal-github-secrets-action/.github/actions/push_repo@main #@@@

      #@@@ - name: Trigger ArgoCD to sync the app and wait for it to complete
      #@@@   env:
      #@@@     ARGOCD_SERVER: kube-aws-grcp-argocd.shared.bbyhealth.com
      #@@@     ARGOCD_AUTH_TOKEN: ${{ secrets.KUBE360_AWS_ARGOCD_AUTH_TOKEN }}
      #@@@   run: scripts/sync_app.sh "${{ inputs.argocd_app }}" dev
