name: Test workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Test action
        uses: borsboom/seal-github-secrets-action/.github/actions/test@main
        with:
          ARGOCD_BASE_REF: test-base-ref