name: Seal Github secrets

on:
  workflow_call:
    inputs:
      kubernetes_namespace:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update sealed secrets from Github secrets
        uses: borsboom/seal-github-secrets-action/.github/actions/seal-github-secrets@main #TODO: SPECIFY TAG?
        with:
          kubernetes_namespace: ${{ inputs.kubernetes_namespace }}
          environment: ${{ inputs.environment }}
          github_secrets_json: ${{ toJSON(secrets) }}
      - name: Commit and push changes
        run: |
          git add -A
          if [[ "$(git diff --name-only --staged)" == "" ]]; then
            echo "No changes; not committing or pushing" >&2
            exit 0
          fi
          git config user.name "Github Actions"
          git config user.email "github@bbyhealth.com"
          git commit -m "Updated sealed secrets from Github secrets in ${{ inputs.environment }} environment"

          # If the push fails, this rebases and tries again since it's likely
          # that another job has pushed to the repo since it was checked out
          while ! git push; do
            echo "Push failed; rebasing and trying again" >&2
            sleep $(bc -l <<< "scale=3; $(((1 + $RANDOM % 1000))) * 5 / 1000")
            git pull --rebase
          done
