name: Seal Github secrets for all environments

on:
  workflow_call:
    inputs:
      kubernetes_namespace:
        type: string
        required: true

jobs:

  dev_environment:
    name: Dev environment
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      environment: dev
      kubernetes_namespace: ${{ inputs.kubernetes_namespace }}

  test_environment:
    name: Test environment
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      environment: test
      kubernetes_namespace: ${{ inputs.kubernetes_namespace }}

  staging_environment:
    name: Staging environment
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      environment: staging
      kubernetes_namespace: ${{ inputs.kubernetes_namespace }}

  prod_environment:
    name: Prod environment
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets.yaml@main #TODO SPECIFY TAG
    secrets: inherit
    with:
      environment: prod
      kubernetes_namespace: ${{ inputs.kubernetes_namespace }}

  shared_environment:
    name: Shared Services environment
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      environment: shared
      kubernetes_namespace: ${{ inputs.kubernetes_namespace }}
